2018-08-07 15:23:32,436 ERROR:Exception on /login [GET] [in C:\Python36\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python36\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python36\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Python36\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python36\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\huanri\PycharmProjects\myproject\app\views.py", line 44, in login
    form = LoginForm()
  File "C:\Python36\lib\site-packages\wtforms\form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Python36\lib\site-packages\flask_wtf\form.py", line 88, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "C:\Python36\lib\site-packages\wtforms\form.py", line 278, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Python36\lib\site-packages\wtforms\form.py", line 132, in process
    field.process(formdata)
  File "C:\Python36\lib\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Python36\lib\site-packages\flask_wtf\csrf.py", line 134, in generate_csrf_token
    token_key=self.meta.csrf_field_name
  File "C:\Python36\lib\site-packages\flask_wtf\csrf.py", line 47, in generate_csrf
    setattr(g, field_name, s.dumps(session[field_name]))
  File "C:\Python36\lib\site-packages\itsdangerous.py", line 565, in dumps
    payload = want_bytes(self.dump_payload(obj))
  File "C:\Python36\lib\site-packages\itsdangerous.py", line 847, in dump_payload
    json = super(URLSafeSerializerMixin, self).dump_payload(obj)
  File "C:\Python36\lib\site-packages\itsdangerous.py", line 550, in dump_payload
    return want_bytes(self.serializer.dumps(obj))
  File "C:\Python36\lib\site-packages\itsdangerous.py", line 51, in dumps
    return json.dumps(obj, separators=(',', ':'))
  File "C:\Python36\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Python36\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python36\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Python36\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable
2018-08-07 15:23:49,616 ERROR:Exception on /login [GET] [in C:\Python36\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python36\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python36\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Python36\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python36\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\huanri\PycharmProjects\myproject\app\views.py", line 44, in login
    form = LoginForm()
  File "C:\Python36\lib\site-packages\wtforms\form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Python36\lib\site-packages\flask_wtf\form.py", line 88, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "C:\Python36\lib\site-packages\wtforms\form.py", line 278, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Python36\lib\site-packages\wtforms\form.py", line 132, in process
    field.process(formdata)
  File "C:\Python36\lib\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Python36\lib\site-packages\flask_wtf\csrf.py", line 134, in generate_csrf_token
    token_key=self.meta.csrf_field_name
  File "C:\Python36\lib\site-packages\flask_wtf\csrf.py", line 47, in generate_csrf
    setattr(g, field_name, s.dumps(session[field_name]))
  File "C:\Python36\lib\site-packages\itsdangerous.py", line 565, in dumps
    payload = want_bytes(self.dump_payload(obj))
  File "C:\Python36\lib\site-packages\itsdangerous.py", line 847, in dump_payload
    json = super(URLSafeSerializerMixin, self).dump_payload(obj)
  File "C:\Python36\lib\site-packages\itsdangerous.py", line 550, in dump_payload
    return want_bytes(self.serializer.dumps(obj))
  File "C:\Python36\lib\site-packages\itsdangerous.py", line 51, in dumps
    return json.dumps(obj, separators=(',', ':'))
  File "C:\Python36\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Python36\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python36\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Python36\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable
2018-08-07 15:25:58,473 ERROR:Exception on /login [GET] [in C:\Python36\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python36\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python36\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Python36\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python36\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\huanri\PycharmProjects\myproject\app\views.py", line 44, in login
    form = LoginForm()
  File "C:\Python36\lib\site-packages\wtforms\form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Python36\lib\site-packages\flask_wtf\form.py", line 88, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "C:\Python36\lib\site-packages\wtforms\form.py", line 278, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Python36\lib\site-packages\wtforms\form.py", line 132, in process
    field.process(formdata)
  File "C:\Python36\lib\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Python36\lib\site-packages\flask_wtf\csrf.py", line 134, in generate_csrf_token
    token_key=self.meta.csrf_field_name
  File "C:\Python36\lib\site-packages\flask_wtf\csrf.py", line 47, in generate_csrf
    setattr(g, field_name, s.dumps(session[field_name]))
  File "C:\Python36\lib\site-packages\itsdangerous.py", line 565, in dumps
    payload = want_bytes(self.dump_payload(obj))
  File "C:\Python36\lib\site-packages\itsdangerous.py", line 847, in dump_payload
    json = super(URLSafeSerializerMixin, self).dump_payload(obj)
  File "C:\Python36\lib\site-packages\itsdangerous.py", line 550, in dump_payload
    return want_bytes(self.serializer.dumps(obj))
  File "C:\Python36\lib\site-packages\itsdangerous.py", line 51, in dumps
    return json.dumps(obj, separators=(',', ':'))
  File "C:\Python36\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Python36\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python36\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Python36\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable
